export const DATA_SOURCE = 'DATA_SOURCE';

export const APPOINTMENT_DETAIL_REPOSITORY = 'APPOINTMENT_DETAIL_REPOSITORY';
export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY';
export const DOCTOR_REPOSITORY = 'DOCTOR_REPOSITORY';
export const MEDICAL_RECORD_REPOSITORY = 'MEDICAL_RECORD_REPOSITORY';
export const PATIENT_REPOSITORY = 'PATIENT_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const SPECIALITY_REPOSITORY = 'SPECIALITY_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';

export const jwtConstants = {
  secret: 'dgyusahfoidsjdoi3854$#"$%dnujsahe',
};
